// 文件路径: Editor/RoadEditorUtility.cs
using UnityEngine;
using UnityEditor;
using System.IO;

namespace RoadSystem.Editor
{
    public static class RoadEditorUtility
    {
        private const string AutoGeneratedLayerPath = "Assets/RoadCreator/Generated/TerrainLayers";

        public static TerrainLayer GetOrCreateTerrainLayerFromMaterial(Material material)
        {
            if (material == null || !material.HasProperty("_MainTex") || material.mainTexture == null)
            {
                return null;
            }

            // 确保目录存在
            if (!Directory.Exists(AutoGeneratedLayerPath))
            {
                Directory.CreateDirectory(AutoGeneratedLayerPath);
            }

            var texture = material.mainTexture;
            string assetPath = Path.Combine(AutoGeneratedLayerPath, $"TL_{texture.name}.asset");

            // 检查是否已存在
            TerrainLayer existingLayer = AssetDatabase.LoadAssetAtPath<TerrainLayer>(assetPath);
            if (existingLayer != null)
            {
                // 可选：检查属性是否一致，不一致则更新
                if (existingLayer.diffuseTexture != texture ||
                    !Mathf.Approximately(existingLayer.tileSize.x, 1f / material.mainTextureScale.x) ||
                    !Mathf.Approximately(existingLayer.tileSize.y, 1f / material.mainTextureScale.y))
                {
                    // 更新现有资源
                    UpdateTerrainLayer(existingLayer, material);
                }
                return existingLayer;
            }

            // 如果不存在，则创建新的
            Debug.Log($"<color=green>自动创建 TerrainLayer: {assetPath}</color>");
            TerrainLayer newLayer = new TerrainLayer();
            UpdateTerrainLayer(newLayer, material);

            AssetDatabase.CreateAsset(newLayer, assetPath);
            AssetDatabase.SaveAssets();

            return newLayer;
        }

        private static void UpdateTerrainLayer(TerrainLayer layer, Material material)
        {
            layer.diffuseTexture = material.mainTexture as Texture2D;

            // Tiling 在 Shader 中是 _MainTex_ST (scale.xy, offset.zw)
            // TerrainLayer.tileSize 是纹理重复多少次来填满一个单位
            // 所以 tiling.x = 1 / tileSize.x
            // 因此 tileSize.x = 1 / tiling.x
            float tileX = (material.mainTextureScale.x == 0) ? 1f : 1f / material.mainTextureScale.x;
            float tileY = (material.mainTextureScale.y == 0) ? 1f : 1f / material.mainTextureScale.y;
            layer.tileSize = new Vector2(tileX, tileY);

            // 你还可以从材质中同步法线贴图、金属度等属性
            if (material.HasProperty("_BumpMap") && material.GetTexture("_BumpMap") != null)
            {
                layer.normalMapTexture = material.GetTexture("_BumpMap") as Texture2D;
            }

            if (material.HasProperty("_Metallic"))
            {
                layer.metallic = material.GetFloat("_Metallic");
            }

            if (material.HasProperty("_Glossiness"))
            {
                layer.smoothness = material.GetFloat("_Glossiness");
            }

            EditorUtility.SetDirty(layer);
        }
    }
}